theme: jekyll-theme-dinky

title: "CS 4873C, Spring 2021: Computing, Society, & Professionalism"
description: A class for CS majors on how to be a responsible and ethical computing professional. 

show_downloads: false