theme: jekyll-theme-minimal

title: "CS 4873C Spring'21"
description: "Computing, Society, & Professionalism"
logo: header-image-1.jpg

show_downloads: false


plugins:
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: true